name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'gradual-verification/silicon-gv'
          path: './silicon'
      - uses: actions/checkout@v3
        with:
          repository: 'gradual-verification/silver-gv'
          path: './silicon/silver'
      - name: Test
        run: sbt test