name: Assembly
on: [ workflow_dispatch ]
permissions:
  contents: read
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'gradual-verification/silicon-gv'
          path: './silicon'
      - uses: actions/checkout@v3
        with:
          repository: 'gradual-verification/silver-gv'
          path: './silicon/silver'
      - name: Assembly
        run: sbt assembly
      - name: Execution
        run: java -Xss15M -Xmx8G -jar target/scala-2.12/gvc0-assembly-0.1.0-SNAPSHOT.jar --config=./study/config/config.xml --execute --nickname=${{ runner.name }} --db-url=$DB_URL --db-user=$DB_USER --db-pass=$DB_PASSWORD --version=$GITHUB_SHA